#!/bin/sh

#hostname
export hostN="R-RTR"


export if1N="ens192"
export if1IP="192.168.10.2"
export if1Mask="255.255.255.252"
export if1CIDR="/30"
export if2N="ens224"
export if2IP="192.168.100.1"
export if2Mask="255.255.255.0"
export if2CIDR="/24"
export defGW="192.168.10.1"
export cleanupswitch=0

    #base setup
echo "Setting hostname and enabling ipforwarding..."
echo $hostN > /etc/hostname
echo net.ipv4.ip_forward=1 > /etc/sysctl.conf
#sed -i.bak 's%files dns%dns files%g' /etc/nsswitch.conf

#ip config
ipConfig() {
echo -n "Replacing net config... "
cat > /etc/sysconfig/network-scripts/ifcfg-$if1N << EOF
DEVICE=$if1N
ONBOOT=yes
IPADDR=$if1IP
NETMASK=$if1Mask
GATEWAY=$defGW
EOF
echo -n $if1N/
ifdown $if1N > /etc/null
ifup $if1N > /etc/null
cat > /etc/sysconfig/network-scripts/ifcfg-$if2N << EOF
DEVICE=$if2N
ONBOOT=yes
IPADDR=$if2IP
NETMASK=$if2Mask
EOF
echo $if2N
ifdown $if2N > /etc/null
ifup $if2N > /etc/null
}

baseCentOS() {
    echo "Disabling firewall and SELinux..."
    systemctl disable -q --now firewalld #allow pings
    sed -i.bak "s/SELINUX=.*/SELINUX=disabled/g" /etc/selinux/config
    echo "Mounting disks..."
	mkdir /media/cdrom
	mount -r /dev/sr1 /media/cdrom
	mkdir /media/CentOS
	mount -r /dev/sr0 /media/CentOS
	echo "Installing packages..."
	yum --disablerepo=* --enablerepo=c7-media -q makecache >/dev/null 2>&1
	yum --disablerepo=* --enablerepo=c7-media -q -y install tcpdump net-tools vim lynx bind-utils nfs-utils cifs-utils openssh-server nano>/dev/null 2>&1
	yum --disablerepo=* --enablerepo=c7-media -y install $(find /media/ -name sshpass*) $(find /media/ -name frr*) $(find /media/ -name libyang*) >/dev/null 2>&1
	echo "Packages installed"
}

hosts() {
	echo "Adding hostnames to /etc/hosts"
	cat >> /etc/hosts << EOF
10.10.10.10	ISP
10.10.10.1	L-FW
20.20.20.5	OUT-CLI
20.20.20.100	R-FW
172.16.20.10	L-SRV
172.16.50.2	L-RTR-A
#172.16.100.61	L-CLI-A
172.16.55.2	L-RTR-B
172.16.200.61	L-CLI-B
192.168.20.10	R-SRV
192.168.10.2	R-RTR
192.168.100.100	R-CLI
EOF
}

sshdEdit() {
	echo "Permitting root login"
	sed -i.bak "s/#PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config
	echo "Restarting sshd..."
	systemctl restart sshd
}

ospf() {
	echo "Configuring OSPF"
	sed -i.bak "s/ospfd.*/ospfd=yes/g" /etc/frr/daemons
	sed -i.bak "s/zebra.*/zebra=yes/g" /etc/frr/daemons
	systemctl restart frr
	systemctl enable frr
	cat > /etc/frr/frr.conf << EOF
frr version 6.0.2
frr defaults traditional
hostname $hostN
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router-id 5.5.5.5
!
router ospf
 passive-interface ens224
 network 192.168.10.0/30 area 0
 network 192.168.100.0/24 area 0
!
line vty
!
EOF
	systemctl restart frr
}



cleanup() {
	echo "Cleaning up and disabling history..."
	echo 'set +o history' >> /etc/profile
	history -c
}

sshdEdit
ipConfig
baseCentOS
hosts
ospf

if [[ $cleanupswitch == 1 ]]; then cleanup; fi

echo DONE
rm -f $0
sleep 60
reboot
